version: "3"
services:
  react-frontend:
    build: ./ui
    ports:
      - "3000:3000"
  node-middleware:
    build: ./node_server
    ports:
      - "5500:5500"
    depends_on:
      - java-backend
  java-backend:
    build: ./servlet_db
    ports:
      - "8080:8080"
